// 平台特定的发布设置类型定义

export type Platform = 'wechat' | 'zhihu' | 'juejin' | 'zsxq' | 'csdn' | 'xiaohongshu';

// 基础发布设置
export interface BasePlatformSettings {
  id: string;
  name: string;
  platform: Platform;
  isDefault?: boolean;
  authorName?: string;
  autoGenerateDigest?: boolean;
  headerContent?: string;
  footerContent?: string;
}

// 平台特定配置（暂时保持简单，只有基础字段）
export interface PlatformConfig {
  // 预留给未来扩展的平台特定字段
  [key: string]: any;
}

// 完整的平台设置
export interface PlatformSettings extends BasePlatformSettings {
  platformConfig?: PlatformConfig;
}

// 简化的平台特定设置类型
export interface WechatSettings extends BasePlatformSettings {
  platform: 'wechat';
}

export interface ZhihuSettings extends BasePlatformSettings {
  platform: 'zhihu';
}

export interface JuejinSettings extends BasePlatformSettings {
  platform: 'juejin';
}

export interface ZsxqSettings extends BasePlatformSettings {
  platform: 'zsxq';
  groupIds?: string[]; // 知识星球ID列表，支持多个星球
}

// 平台信息
export interface PlatformInfo {
  id: Platform;
  name: string;
  icon: string;
  color: string;
  description: string;
  supportedFeatures: string[];
}

// 平台配置映射
export const PLATFORM_CONFIGS: Record<Platform, PlatformInfo> = {
  wechat: {
    id: 'wechat',
    name: '微信公众号',
    icon: '📱',
    color: 'bg-green-500',
    description: '微信公众号文章发布',
    supportedFeatures: ['原创标记', '赞赏功能', '留言功能', '精选文章', '定制卡片']
  },
  zhihu: {
    id: 'zhihu',
    name: '知乎',
    icon: '🔵',
    color: 'bg-blue-500',
    description: '知乎专栏文章发布',
    supportedFeatures: ['专栏选择', '标签设置', '话题关联', '评论设置']
  },
  juejin: {
    id: 'juejin',
    name: '掘金',
    icon: '⚡',
    color: 'bg-cyan-500',
    description: '掘金技术文章发布',
    supportedFeatures: ['分类选择', '标签设置', '难度等级', '封面图片']
  },
  zsxq: {
    id: 'zsxq',
    name: '知识星球',
    icon: '🌟',
    color: 'bg-yellow-500',
    description: '知识星球文章和主题发布',
    supportedFeatures: ['多星球发布', '富文本编辑', 'Markdown支持', '文章模式', '主题模式']
  },
  csdn: {
    id: 'csdn',
    name: 'CSDN',
    icon: '🅲',
    color: 'bg-red-500',
    description: 'CSDN 博客文章发布',
    supportedFeatures: ['Markdown支持', '代码高亮', '分类/标签']
  },
  xiaohongshu: {
    id: 'xiaohongshu',
    name: '小红书',
    icon: '🍓',
    color: 'bg-rose-500',
    description: '小红书图文笔记发布',
    supportedFeatures: ['富文本编辑', '话题标签', '图片适配']
  }
};

// 获取平台默认配置（暂时返回空对象，未来扩展时添加平台特定字段）
export function getDefaultPlatformConfig(platform: Platform): PlatformConfig {
  return {};
}
